import { useState } from "react";
import "./App.css";
import About from "./About";

function DropZone() {
  const [dragging, setDragging] = useState(false);
  const [file, setFile] = useState(null);

  const handleDragOver = (e) => {
    e.preventDefault();
    setDragging(true);
  };

  const handleDragLeave = () => setDragging(false);

  const handleDrop = (e) => {
    e.preventDefault();
    setDragging(false);
    const dropped = e.dataTransfer.files[0];
    if (dropped) setFile(dropped);
  };

  const handleFileInput = (e) => {
    const selected = e.target.files[0];
    if (selected) setFile(selected);
  };



  return (
    <div
      className={`drop-zone ${dragging ? "drop-zone--active" : ""} ${file ? "drop-zone--filled" : ""}`}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <input
        type="file"
        accept="audio/*"
        id="file-input"
        className="file-input"
        onChange={handleFileInput}
      />

      {!file ? (
        <>
          <div className="drop-icon">
            <svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
              <rect x="8" y="6" width="32" height="36" rx="4" strokeWidth="1.5" className="icon-rect"/>
              <path d="M24 18v12M18 24h12" strokeWidth="1.5" strokeLinecap="round" className="icon-plus"/>
              <path d="M16 36h16" strokeWidth="1.5" strokeLinecap="round" className="icon-line"/>
            </svg>
          </div>
          <p className="drop-label">Drop an audio file here</p>
          <p className="drop-sub">MP3, WAV, FLAC, M4A supported</p>
          <label htmlFor="file-input" className="browse-btn">
            Browse files
          </label>
        </>
      ) : (
        <>
          <div className="file-icon">
            <svg viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
              <rect x="8" y="6" width="32" height="36" rx="4" strokeWidth="1.5" className="icon-rect"/>
              <path d="M18 26l4 4 8-8" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="icon-check"/>
            </svg>
          </div>
          <p className="drop-label">{file.name}</p>
          <p className="drop-sub">{(file.size / (1024 * 1024)).toFixed(2)} MB</p>
          <button className="browse-btn" onClick={() => setFile(null)}>
            Remove
          </button>
        </>
      )}
    </div>
  );
}

export default function App() {

  const [currentPage, setCurrentPage] = useState('home');

  if (currentPage === 'about') {
    return <About onBack={() => setCurrentPage('home')} />;
  }

  return (
    <div className="app">
      <header className="header">
        <div className="header-inner">
          <div className="logo">
            <svg viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg" width="28" height="28">
              <rect width="32" height="32" rx="8" className="logo-bg"/>
              <path d="M10 22V16M14 22V12M18 22V10M22 22V16" strokeWidth="1.8" strokeLinecap="round" className="logo-bars"/>
            </svg>
            <span className="logo-text">AudioVerify</span>
          </div>
          <nav className="nav">
			<a href="#" className={`nav-link ${currentPage === 'home' ? 'nav-link--active' : ''}`} onClick={() => setCurrentPage('home')}>Analyze</a>
			<a href="#" className={`nav-link ${currentPage === 'about' ? 'nav-link--active' : ''}`} onClick={() => setCurrentPage('about')}>About</a>
          </nav>
        </div>
      </header>

      <main className="main">
        <section className="hero">
          <p className="hero-badge">AI Detection</p>
          <h1 className="hero-title">Is this audio real?</h1>
          <p className="hero-sub">
            Upload an audio file and our model will tell you whether it was
            generated by AI or recorded by a human.
          </p>
        </section>

        <DropZone />

      <footer className="footer">
        <p>© 2026 AudioVerify. All rights reserved.</p>
        <p className="fmi-tag">Built with ❤️ for FMI Hackathon</p>
      </footer>
	  
      </main>
    </div>
  );
}
